edition = "2021"
fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 130
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 0
short_array_element_width_threshold = 10
tab_spaces = 3
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
