template struct Result<bool>;
template struct Result<const std::vector<cv::Mat>*>;
template struct Result<cv::KeyPoint>;
template struct Result<cv::Mat*>;
template struct Result<cv::Ptr<cv::DescriptorMatcher>*>;
template struct Result<cv::Ptr<cv::Feature2D>*>;
template struct Result<cv::ccalib::CustomPattern*>;
template struct Result<cv::multicalib::MultiCameraCalibration*>;
template struct Result<cv::multicalib::MultiCameraCalibration::edge*>;
template struct Result<cv::multicalib::MultiCameraCalibration::vertex*>;
template struct Result<cv::randpattern::RandomPatternCornerFinder*>;
template struct Result<cv::randpattern::RandomPatternGenerator*>;
template struct Result<double>;
template struct Result<int>;
template struct Result<std::vector<cv::Mat>*>;
