script_dir="$(dirname "$(readlink -f "$BASH_SOURCE")")"

. "$script_dir/config.sh"

export PKG_CONFIG_PATH="$OPENCV_32_PKG_CONFIG_PATH"
export OPENCV_PACKAGE_NAME="$OPENCV_32_OPENCV_PACKAGE_NAME"
export LD_LIBRARY_PATH="$OPENCV_32_LD_LIBRARY_PATH"
export OPENCV_INCLUDE_PATHS="$OPENCV_32_OPENCV_INCLUDE_PATHS"
